---
title: "Overview"
author: "Karishma Raj"
date: "2023-03-03"
output: html_document
---

#The Effect of Climate Change on Sea Level Rise

Climate change has affected our world in countless ways, one of the most prominent ways being ***rising sea levels***. Our project's goals are to address sea level rise by focusing on its _causes_, _projection_ over the next few years, and its _effects_ on people. 

We intend on answering our questions about rising sea levels with data sets that come from reputable sources that have extensively researched this topic. One data set from NASA, which we will be using, describes the ***causes of sea level rise***. 
total land impacted, 
population impacted by 

We hope to deliver this information to students in high school or college who are interested in learning more about climate change. It is important that younger generations learn about the effects of climate change since they will be responsible for dealing with it and making a change in the future. 















